### ISSUE TITLE
[Android Bootcamp] Project 4: Simple Twitter Client - Ready for Review

### ISSUE THREAD

**Issue by lwhsu** [lwhsu/SimpleTwitterClient#1]
My app is complete, please review.

BTW I have a question about ActiveAndroid: I wanted to save Tweets-Users as many-to-one relationship, but the result is not what I want.  

What I want:

Tweets:

| uid | body | user_id (FK Users.uid) |
| --- | --- | --- |
| 1 | body1 | 1 |
| 2 | body2 | 1 |
| 3 | body3 | 2 |

Users:

| uid | name |
| --- | --- |
| 1 | name1 |
| 2 | name2 |

And hope `new Select().from(Tweet.class).orderBy("uid DESC").execute();` gives a `List<Tweets>` with all 3 tweets.  However, I only got 2 tweets, which uid are 1 and 3 (belong to different users).

It seems that there is another invisible primary key in each table and cannot be customized (see pardom/ActiveAndroid issue 22).  And when I save tweets from the same user at:

https://github.com/lwhsu/SimpleTwitterClient/blob/a2b9dfaa5ebb6d608f8f79200737e28d3f90f052/src/org/lwhsu/android/basictwitter/TimelineActivity.java#L72

The "old user" is just replaced by the "new user", then the tweet belongs to the "old user" is deleted, because of these settings:

https://github.com/lwhsu/SimpleTwitterClient/blob/2115a0ae313738fc47cb5f6606d48e9c5fbd457e/src/org/lwhsu/android/basictwitter/models/User.java#L12
https://github.com/lwhsu/SimpleTwitterClient/blob/2115a0ae313738fc47cb5f6606d48e9c5fbd457e/src/org/lwhsu/android/basictwitter/models/Tweet.java#L31

i.e., the real tables in the SQLite are like this:

Tweets:

| uid | body | user_id | pkey (FK Users.pkey) |
| --- | --- | --- | --- |
| 2 | body2 | 1 | 2 |
| 3 | body3 | 3 | 3 |

Users:

| uid | name | pkey |
| --- | --- | --- |
| 1 | name1 | 2 |
| 3 | name2 | 3 |

where `(uid, body, user_id, pkey) = (1, body1, 1, 1)` and `(uid, name, pkey) = (1, name1, 1)` are deleted during insertion of user `(uid, name, pkey)  = (1, name1, 2)`, because `Users.uid` is unique.  Is my guess making sense?

For now, I have to mark uid in `Users` table not unique: https://github.com/lwhsu/SimpleTwitterClient/commit/a2b9dfaa5ebb6d608f8f79200737e28d3f90f052 , but this is wasting storage.

Is there any better way to solve this?

Thanks!

/cc @nidhi1608 @thecodepath

Li-Wen Hsu lwhsu@yahoo-inc.com

**Comment by nidhi1608** [comment]
Thats right, ActiveAndroid does create an auto-incrementing primary key for your tables. Refer the [ActiveAndroid Wiki](https://github.com/pardom/ActiveAndroid/wiki/Creating-your-database-model).

This is unfortunate because as you mentioned, the constraints specified replaces the new User with old User and in the process the "id" column gets updated as well. There is a way to solve this, but its a bit manual. Instead of defining the foreign key and the relationship with User in the Tweet model, you can just have a reference to userId in Tweet and then fetch the user based on this userId. This will also require you to save the User object before you call save on Tweet object. 

In addition to this, you can also store the users in a static HashMap or any key-value object and operate on that to save unique users to the database.

**Comment by nidhi1608** [comment]
:+1: Congrats on completing the assignment! Nice work overall. I have provided a detailed [Feedback Guide here](https://gist.github.com/nesquena/a41220c54c9550f69599) which covers the most common issues with this submitted project. Read through the feedback guide point-by-point to determine how you could improve your submission. 

Let us know if you have any other thoughts or questions about this assignment. Hopefully by now you feel pretty comfortable with all the major pieces to basic Android apps (Views, Controllers, Models, Authentication, API Communication, Preferences, ActionBar, et al) and see how they all fit together.
